name: add to project senzing github organization

on:
  issues:
    types:
      - opened
      - reopened

permissions: {}

jobs:
  add-to-project:
    permissions:
      repository-projects: write
    secrets:
      PROJECT_RW_TOKEN: ${{ secrets.SENZING_GITHUB_PROJECT_RW_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/add-to-project.yaml@v4
    with:
      project-number: ${{ vars.SENZING_GITHUB_ORGANIZATION_PROJECT }}
      org: ${{ vars.SENZING_GITHUB_ACCOUNT_NAME }}

  slack-notification:
    needs: [add-to-project]
    if: ${{ always() && contains(fromJSON('["failure", "cancelled"]'), needs.add-to-project.result) }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
    uses: senzing-factory/build-resources/.github/workflows/build-failure-slack-notification.yaml@v4
    with:
      job-status: ${{ needs.add-to-project.result }}
