name: Move pr to done dependabot

on:
  pull_request:
    branches: [main]
    types: [closed]

permissions: {}

jobs:
  move-pr-to-done-dependabot:
    permissions:
      repository-projects: write
    secrets:
      SENZING_GITHUB_PROJECT_RW_TOKEN: ${{ secrets.SENZING_GITHUB_PROJECT_RW_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/move-pr-to-done-dependabot.yaml@v3
    with:
      project: ${{ vars.SENZING_GITHUB_ORGANIZATION_PROJECT }}
